### ISSUE TITLE
Missing method in doctor

### ISSUE THREAD

**Issue by Red-Menace** [amirrajan/rubymotion-templates#50]
In the last commit you missed changing `raise_error` (which has been changed/removed) in the `print_environment_info` method of `motion/doctor.rb`.  This will barf if, say, Homebrew is not installed.

**Comment by andrewhavens** [comment]
@Red-Menace I'll take a look at this.

**Comment by andrewhavens** [comment]
@Red-Menace Can you post a screenshot (or copy/paste) the output that you are seeing when you have this error?

**Comment by Red-Menace** [comment]
I don't use Homebrew, so when `motion doctor` tries to get the installed packages using `brew list`, it fails with:

```
menace ~: motion doctor
= ENVIRONMENT INFO =
Swift Runtime:        ✅
RubyMotion Templates: ✅
RubyMotion Commands:  ✅
= RubyMotion =
version:      7.6
osx sdks:     10.10, 10.11, 10.12, 10.13, 10.14, 10.15, 10.16, 10.9, librubymotion-repl.dylib
ios sdks:     10.0, 10.1, 10.2, 10.3, 11.0, 11.1, 11.2, 11.3, 11.4, 12.0, 12.1, 12.2, 12.4, 13.0, 13.1, 13.2, 13.4, 13.5, 13.6, 14.0
tv sdks:      10.0, 10.1, 10.2, 11.0, 11.1, 11.2, 11.3, 11.4, 12.0, 12.1, 12.2, 12.4, 13.0, 13.2, 13.4, 14.0
watch sdks:   3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 5.3, 6.0, 6.1, 6.2, 7.0
android sdks: 21, 22, 23, 24, 25, 26, 27, 28
= xcodebuild =
Xcode 10.3
Build version 10G8
= clang =
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
= xcode-select =
version: xcode-select version 2354.
path:    /Applications/Xcode.app/Contents/Developer
= Xcode =
osx platform:   MacOSX.sdk, MacOSX10.12.sdk, MacOSX10.13.sdk, MacOSX10.14.sdk
ios platform:   iPhoneOS.sdk, iPhoneOS12.4.sdk
tv platform:    AppleTVOS.sdk, AppleTVOS12.4.sdk
watch platform: WatchOS.sdk, WatchOS5.3.sdk
= Android =
android sdks:    (none)
android ndk:     (none)
= Java =
No Java runtime present, requesting install.
= MacOS =
System Version: macOS 10.14.6 (18G6020)
= ENV =
RUBYMOTION_ANDROID_SDK=
RUBYMOTION_ANDROID_NDK=
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
= Ruby Manager =
rvm:    
rbenv:  /Users/menace/.rbenv/libexec/rbenv
chruby: 
asdf:   
= Homebrew =
Traceback (most recent call last):
	6: from /usr/local/bin/motion:22:in `<main>'
	5: from /Library/RubyMotion/lib/motion/command.rb:105:in `run'
	4: from /Library/RubyMotion/vendor/CLAide/lib/claide/command.rb:277:in `run'
	3: from /Library/RubyMotion/lib/motion/command/doctor.rb:32:in `run'
	2: from /Users/menace/.rubymotion/rubymotion-templates/doctor.rb:14:in `execute'
	1: from /Users/menace/.rubymotion/rubymotion-templates/doctor.rb:112:in `print_environment_info'
/Users/menace/.rubymotion/rubymotion-templates/doctor.rb:112:in ``': No such file or directory - brew (Errno::ENOENT)
	6: from /usr/local/bin/motion:22:in `<main>'
	5: from /Library/RubyMotion/lib/motion/command.rb:105:in `run'
	4: from /Library/RubyMotion/vendor/CLAide/lib/claide/command.rb:277:in `run'
	3: from /Library/RubyMotion/lib/motion/command/doctor.rb:32:in `run'
	2: from /Users/menace/.rubymotion/rubymotion-templates/doctor.rb:14:in `execute'
	1: from /Users/menace/.rubymotion/rubymotion-templates/doctor.rb:44:in `print_environment_info'
/Users/menace/.rubymotion/rubymotion-templates/doctor.rb:115:in `rescue in print_environment_info': undefined method `raise_error' for #<Motion::Project::Doctor:0x00007f94210cad70> (NoMethodError)

```

Looking at the history, `raise_error` appears to have been used previously to output the error.  The outputs were changed with the last commit, and it just appears one of the old calls was missed.

**Comment by andrewhavens** [comment]
@Red-Menace I pushed an update. Can you run `motion repo` and copy/paste the output here?

**Comment by Red-Menace** [comment]
Looks like that got it:
```
menace ~: motion doctor
= ENVIRONMENT INFO =
Swift Runtime:        ✅
RubyMotion Templates: ✅
RubyMotion Commands:  ✅
= RubyMotion =
version:      7.6
osx sdks:     10.10, 10.11, 10.12, 10.13, 10.14, 10.15, 10.16, 10.9, librubymotion-repl.dylib
ios sdks:     10.0, 10.1, 10.2, 10.3, 11.0, 11.1, 11.2, 11.3, 11.4, 12.0, 12.1, 12.2, 12.4, 13.0, 13.1, 13.2, 13.4, 13.5, 13.6, 14.0
tv sdks:      10.0, 10.1, 10.2, 11.0, 11.1, 11.2, 11.3, 11.4, 12.0, 12.1, 12.2, 12.4, 13.0, 13.2, 13.4, 14.0
watch sdks:   3.0, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 5.3, 6.0, 6.1, 6.2, 7.0
android sdks: 21, 22, 23, 24, 25, 26, 27, 28
= xcodebuild =
Xcode 10.3
Build version 10G8
= clang =
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
= xcode-select =
version: xcode-select version 2354.
path:    /Applications/Xcode.app/Contents/Developer
= Xcode =
osx platform:   MacOSX.sdk, MacOSX10.12.sdk, MacOSX10.13.sdk, MacOSX10.14.sdk
ios platform:   iPhoneOS.sdk, iPhoneOS12.4.sdk
tv platform:    AppleTVOS.sdk, AppleTVOS12.4.sdk
watch platform: WatchOS.sdk, WatchOS5.3.sdk
= Android =
android sdks:    (none)
android ndk:     (none)
= Java =
No Java runtime present, requesting install.
= MacOS =
System Version: macOS 10.14.6 (18G6020)
= ENV =
RUBYMOTION_ANDROID_SDK=
RUBYMOTION_ANDROID_NDK=
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
= Ruby Manager =
rvm:    
rbenv:  /Users/menace/.rbenv/libexec/rbenv
chruby: 
asdf:   
= Ruby =
/Users/menace/.rbenv/versions/2.7.0/bin/ruby
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
= Homebrew =
Homebrew is not installed.
======================================================================
* Success! `motion doctor` ran successfully and found no issues.

Still need help? Join us on Slack: http://slack.rubymotion.com
======================================================================

```

**Comment by andrewhavens** [comment]
Thanks @Red-Menace !
